{{- range .Values.storageClasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
  {{- if or .annotations .isDefaultClass }}
  annotations:
    {{- if .isDefaultClass }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "btrfs-csi.labels" $ | nindent 4 }}
provisioner: {{ .provisioner }}
{{- with .parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: {{ .reclaimPolicy }}
allowVolumeExpansion: true
{{- end }}
