apiVersion: apps/v1
kind: Deployment
metadata:
  name: btrfs-csi-controller
  namespace: kube-system
  labels:
    app: btrfs-csi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btrfs-csi-controller
  template:
    metadata:
      labels:
        app: btrfs-csi-controller
    spec:
      serviceAccountName: btrfs-csi-driver
      containers:
        - name: btrfs-csi-driver
          image: localhost:5000/btrfs-csi:latest
          imagePullPolicy: Never
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--controller=true"
            - "--v=5"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "100m"
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--feature-gates=Topology=true"
            - "--extra-create-metadata"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "100m"
      volumes:
        - name: plugin-dir
          emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux