apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: btrfs-local
provisioner: btrfs.csi.k8s.io
parameters:
  # No additional parameters needed for local volumes
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: false